#!/usr/bin/env bash

echo
echo "--------------"
echo "|  RICOCHET  |"
echo "--------------"
echo

print_help(){
  echo
  echo "Run ricochet with one of the following subcommands:"
  echo
  echo "  all      - run all tasks"
  echo "  apps     - install all homebrew and cask packages"
  echo "  dev      - install all ruby gems and npm packages"
  echo "  dotfiles - set up symlinks for all dotfiles"
  echo "  setup    - install osx defaults, cron jobs, and misc files"
  echo "  help     - print this help message"
  echo
}

if [ -z "$1" ]
  then
    echo "No subcommands specified."
    print_help
elif [ "$1" == "help" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]
  then
    print_help
elif [ "$1" == "all" ]
  then
    ansible-playbook ricochet.yml
else
  ansible-playbook ricochet.yml --tags "$1"
fi
